apiVersion: v1
kind: Service
metadata:
  name: {{ include "bastion.fullname" . }}
  labels:
    {{- include "bastion.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "bastion.selectorLabels" . | nindent 4 }}
